# Generated by Django 4.2.3 on 2023-08-15 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_user_created_at_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 15)),
        ),
    ]
