# Generated by Django 4.2.3 on 2023-08-15 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 15)),
        ),
    ]
