# Generated by Django 4.2.3 on 2023-08-15 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_nutrition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
    ]
